### ISSUE TITLE
Creating ARM Template

### ISSUE THREAD

**Issue by writeline** [writeline/BRaaS#1]
Need ARM template to create the whole environment including

- [x] Linux VM with configured Docker
- [x] Azure Files
- [ ] Azure App Service Web Site
- [x] Startup Scripts to provision Linux VM with Azure Files share

**Comment by DanielMeixner** [comment]
Created 1 arm template for our first approach (multiple containers on 1 host). 
Created another arm template for our second approach (1 container on multiple hosts).
